#
# Antizapret VPN (Server)
#

auth = "plain[passwd=/etc/ocserv/antizapret.passwd]"

tcp-port = 53443
udp-port = 53443

run-as-user = nobody
run-as-group = nogroup

socket-file = /run/ocserv-antizapret.socket
occtl-socket-file = /run/occtl-antizapret.socket
pid-file = /run/ocserv-antizapret.pid
use-occtl = true

server-cert = /etc/ocserv/certs/server-cert.pem
server-key = /etc/ocserv/certs/server-key.pem

isolate-workers = true
max-clients = 0
max-same-clients = 1

keepalive = 15
dpd = 60
mobile-dpd = 300
switch-to-tcp-timeout = 25
try-mtu-discovery = true

auth-timeout = 240
idle-timeout = 86400
mobile-idle-timeout = 86400
min-reauth-time = 3
max-ban-score = 0
ban-reset-time = 300
cookie-timeout = 300
deny-roaming = false
rekey-time = 172800
rekey-method = ssl

tls-priorities = "NORMAL:%SERVER_PRECEDENCE:%COMPAT:-VERS-SSL3.0:-VERS-TLS1.0:-VERS-TLS1.1:-VERS-TLS1.2"

device = oc-az
predictable-ips = true
ping-leases = false
cisco-client-compat = true

ipv4-network = 10.29.12.0
ipv4-netmask = 255.255.252.0

dns = 10.29.12.1
tunnel-all-dns = true

#log-level = 1

route = 8.8.8.8/255.255.255.255
route = 8.8.4.4/255.255.255.255

# DO NOT EDIT BELOW THIS LINE
