#
# Full VPN (Server)
#

auth = "plain[passwd=/etc/ocserv/vpn.passwd]"

tcp-port = 53080
udp-port = 53080

run-as-user = nobody
run-as-group = nogroup

socket-file = /run/ocserv-vpn.socket
occtl-socket-file = /run/occtl-vpn.socket
pid-file = /run/ocserv-vpn.pid
use-occtl = true

server-cert = /etc/ocserv/certs/server-cert.pem
server-key = /etc/ocserv/certs/server-key.pem

isolate-workers = true
max-clients = 0
max-same-clients = 1

keepalive = 15
dpd = 60
mobile-dpd = 300
switch-to-tcp-timeout = 25
try-mtu-discovery = true

auth-timeout = 240
idle-timeout = 86400
mobile-idle-timeout = 86400
min-reauth-time = 3
max-ban-score = 0
ban-reset-time = 300
cookie-timeout = 300
deny-roaming = false
rekey-time = 172800
rekey-method = ssl

tls-priorities = "NORMAL:%SERVER_PRECEDENCE:%COMPAT:-VERS-SSL3.0:-VERS-TLS1.0:-VERS-TLS1.1"

device = oc-vpn
predictable-ips = true
ping-leases = false
cisco-client-compat = true

ipv4-network = 10.28.12.0
ipv4-netmask = 255.255.252.0

dns = 1.1.1.1
dns = 1.0.0.1
tunnel-all-dns = true

#log-level = 1
